In [9]:
import os
import pandas as pd
import re
from pathlib import Path
import numpy as np
from datetime import datetime, timezone
import json
import gspread
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow

SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive",
]

CREDENTIALS_PATH = "credentials.json"
TOKEN_PATH = "token.json"

In [10]:
dirs = {
    "instruments_root": r"/Volumes/lab-windingm/data/instruments/behavioural_rigs/plugcamera/", #where all the pupae count folders live, information that could be automatically checked - each folder has a folder called pupae inside of it, then a folder called raw_data where .mp4 videos live of the pupae recs. Manpower is needed to add these videos to the folders in the first place, as this is either done through Dropbox or through rsync
    "shared_root" :r"/Volumes/lab-windingm/home/shared/repos/screen-stats", #i think this is redundant
    "local_beh-rigs": r"/Users/meryv/repos/behavioural-rigs", 

    "final-sheets": r"/Volumes/lab-windingm/home/shared/repos/screen-stats/final-sheets", #these are view only, one master spreadsheet per sub-screen
    "intermediate-sheets": r"/Volumes/lab-windingm/home/shared/repos/screen-stats/intermediate-sheets", #these are not completed yet, still left to do the pupae counts
    
    "mechano-weekly" : r"/Volumes/lab-windingm/home/shared/repos/screen-stats/mechano-screen", #these are edited manually
    "split-weekly" : r"/Volumes/lab-windingm/home/shared/repos/screen-stats/split-screen", 
    "VRDN-weekly" : r"/Volumes/lab-windingm/home/shared/repos/screen-stats/VRDN-screen",
    
    "backup-mechano": r"/Volumes/lab-windingm/home/shared/repos/screen-stats/mechano-backup", #these are never touched 
    "backup-split": r"/Volumes/lab-windingm/home/shared/repos/screen-stats/split-backup", 
    "backup-VRDN" : r"/Volumes/lab-windingm/home/shared/repos/screen-stats/VRDN-backup",

    "plugcamera": r"/Volumes/lab-windingm/home/shared/repos/screen-stats/plugcamera", #not used here
    "notebooks": r"/Volumes/lab-windingm/home/shared/repos/screen-stats/notebooks", 
    
    "fly-lines": r"/Volumes/lab-windingm/home/shared/repos/screen-stats/fly-lines" #sometimes gets updated on Dropbox
}

WEEK_TO_SPREADSHEET_ID = {
    1: "1pLGTVYPtalXG0o81nfcdldW7l_wCYjrAkbaok7Qm1AA", 
    2: "1LyZz-w3hfr1HtEhWeX-Mh7jGxFdMruvkwO_f6CJAFXM", 
    3: "1Qhw80Em3mNXuQzxJDndURJooYMgjBusFIzSk_V5VY7k", 
    4: "1WrWOelZgj5-MBAScA3J1nOvCJ362CMWuvTNuXOvOwnI", 
    5: "1-_ieR_zL29S_yWGH8p5NCDg6I8T8uD8iYOywlqnv8RQ", 
    6: "1p-rRjZKr78O77VeYuWq3zRA74Vjdli2j5pshYnwmJd0", 
    7: "1g8utRFF02OVMsuhlnVtWP37OPk-AR87k7LYKUXkWiY0"
}

SPREADSHEET_TO_EXP_NAME = {
    #date , first part of the weekly sheet name - type of screen
}

In [11]:
#connect to google
def get_gspread_client():
    creds = None
    
    if os.path.exists(TOKEN_PATH):
        creds = Credentials.from_authorized_user_file(TOKEN_PATH, SCOPES)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                CREDENTIALS_PATH,
                SCOPES,
            )
            creds = flow.run_local_server(port=0)

        with open(TOKEN_PATH, "w") as token:
            token.write(creds.to_json())

    return gspread.authorize(creds)

#find pupae count folder - this could be automated so I don't have to write out the name every time - just interested in the screen and the week number, which I input below just in target week. 
def read_pupae_counts(experiment_name, nemo_root=dirs["instruments_root"]):
    predictions_dir = Path(nemo_root) / experiment_name / "pupae" / "predictions"

    if not predictions_dir.exists():
        raise FileNotFoundError(f"Predictions folder not found: {predictions_dir}")
    if not predictions_dir.is_dir():
        raise NotADirectoryError(f"Predictions path is not a folder: {predictions_dir}")

    csv_files = sorted(predictions_dir.glob("*.csv"))

    if len(csv_files) == 0:
        raise FileNotFoundError(f"No CSV files found in: {predictions_dir}")

    return pd.read_csv(csv_files[0])

#not very helpful at the moment, it would be good if this was a utility that did not get uploaded to the end spreadsheet. 
def standardise_missing_values(df):
    out = df.copy()

    missing_like = {
        "",
        "nan",
        "na",
        "n/a",
        "<na>",
        "none",
        "null",
        "nat",
    }

    for col in out.columns:
        if out[col].dtype == "object" or pd.api.types.is_string_dtype(out[col]):
            s = out[col].astype("string").str.strip()
            out[col] = out[col].mask(s.str.lower().isin(missing_like), pd.NA)

    return out

In [12]:
#connecting to the specific weekly spreadsheet
year = "2026"
target_week = 7


client = get_gspread_client()
spreadsheet_id = WEEK_TO_SPREADSHEET_ID[target_week]
spreadsheet = client.open_by_key(spreadsheet_id)
worksheet = spreadsheet.worksheet("Sheet1")
sheet_records = worksheet.get_all_records() #will not work with duplicate columns
sheet_df = pd.DataFrame(sheet_records)
print("Connected to:", spreadsheet.title)
#print("Worksheet:", worksheet.title) #this may be helpful in the future?
sheet_df.head()

Connected to: 2026-07-27_VRDN-screen_week-7

,experimenter,collector,plugcamera,condition,weekly_id,condition_comments,date,time,amendments,comments,recording_time,staging_times,Pupae,pupae_batch_folder,staging_date,last_edit,dataset
0,VM,VM,97.0,ss02758,a1,<NA>,29-07,night,<NA>,<NA>,10:30,16:30-10:00,<NA>,<NA>,29-30/07/2026,<NA>,NaN
1,VM,VM,98.0,ss55093,a2,<NA>,29-07,night,<NA>,<NA>,10:30,16:30-10:00,<NA>,<NA>,29-30/07/2026,<NA>,NaN
2,VM,VM,99.0,ss01624,a3,<NA>,29-07,night,<NA>,<NA>,10:30,16:30-10:00,<NA>,<NA>,29-30/07/2026,<NA>,NaN
3,VM,VM,100.0,ss54410,a4,<NA>,29-07,night,<NA>,<NA>,10:30,16:30-10:00,<NA>,<NA>,29-30/07/2026,<NA>,NaN
4,VM,VM,101.0,ss01267,a5,<NA>,29-07,night,<NA>,<NA>,10:30,16:30-10:00,<NA>,<NA>,29-30/07/2026,<NA>,NaN

In [13]:
match_cols = ["condition", "date", "time"]
weekly_id_cols = ["weekly_id", "date", "time"]

#i cannot get it to depend on the staging_date condition, I am trying to get rid of it - is this possible? I am just trying to tidy up the different columns that might not be needed. 
s = sheet_df["staging_date"].astype("string").str.strip()
has_staging_date = s.notna() & s.ne("")

range_parts = s.str.extract(
    r"^\s*(?P<first_day>\d{1,2})\s*-\s*\d{1,2}/(?P<month>\d{1,2})/(?P<year>\d{4})\s*$"
)

first_date_from_range = (
    range_parts["first_day"].str.zfill(2)
    + "/"
    + range_parts["month"].str.zfill(2)
    + "/"
    + range_parts["year"]
)

first_full_date = s.str.extract(
    r"(?P<first_date>\d{1,2}/\d{1,2}/\d{4})",
    expand=False
)

first_date = first_date_from_range.where(
    range_parts["first_day"].notna(),
    first_full_date
)

parsed_date = pd.to_datetime(
    first_date,
    format="%d/%m/%Y",
    errors="coerce"
)

sheet_df["date"] = pd.NA
sheet_df.loc[has_staging_date, "date"] = parsed_date.dt.strftime("%d-%m")

sheet_df["date"] = sheet_df["date"].astype("string").str.strip()

if "time" not in sheet_df.columns:
        sheet_df["time"] = pd.NA
else: 
        print("Time and date colums already exist")

night_mask = s.str.contains(r"\d\s*-\s*\d", na=False)

sheet_df.loc[has_staging_date & night_mask, "time"] = "night"
sheet_df.loc[has_staging_date & ~night_mask, "time"] = "day"

#make sure they're clean
for col in match_cols:
    if col in sheet_df.columns:
        sheet_df[col] = (
            sheet_df[col]
            .astype("string")
            .str.replace("\u00a0", " ", regex=False)
            .str.strip()
            .str.lower()
        )

sheet_df2 = sheet_df[sheet_df["condition"] == "split-2"].copy()
sheet_df

Time and date colums already exist

,experimenter,collector,plugcamera,condition,weekly_id,condition_comments,date,time,amendments,comments,recording_time,staging_times,Pupae,pupae_batch_folder,staging_date,last_edit,dataset
0,VM,VM,97.0,ss02758,a1,<NA>,29-07,night,<NA>,<NA>,10:30,16:30-10:00,<NA>,<NA>,29-30/07/2026,<NA>,NaN
1,VM,VM,98.0,ss55093,a2,<NA>,29-07,night,<NA>,<NA>,10:30,16:30-10:00,<NA>,<NA>,29-30/07/2026,<NA>,NaN
2,VM,VM,99.0,ss01624,a3,<NA>,29-07,night,<NA>,<NA>,10:30,16:30-10:00,<NA>,<NA>,29-30/07/2026,<NA>,NaN
3,VM,VM,100.0,ss54410,a4,<NA>,29-07,night,<NA>,<NA>,10:30,16:30-10:00,<NA>,<NA>,29-30/07/2026,<NA>,NaN
4,VM,VM,101.0,ss01267,a5,<NA>,29-07,night,<NA>,<NA>,10:30,16:30-10:00,<NA>,<NA>,29-30/07/2026,<NA>,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,VM,VM,281.0,ss24022,b18,<NA>,31-07,day,<NA>,<NA>,16:40,10:30-16:15,27,VM_2026-08-12_VRDN-screen-week7_batch1_f64,31/07/2026,15-10-2026,SS24022_31-07_day_L0.mp4.json
127,VM,VM,282.0,ss04198,b19,<NA>,31-07,day,<NA>,<NA>,16:40,10:30-16:15,122,VM_2026-08-12_VRDN-screen-week7_batch1_f64,31/07/2026,15-10-2026,SS04198_31-07_day_L0.mp4.json
128,VM,VM,283.0,ss38045,b20,<NA>,31-07,day,-1,not enough pupae,16:40,10:30-16:15,32,manual,31/07/2026,<NA>,NaN
129,NaN,NaN,NaN,s21,NaN,NaN,<NA>,night,NaN,NaN,NaN,NaN,63,VM_2026-08-12_VRDN-screen-week7_batch1_f64,NaN,15-10-2026,S21_30-07_night_L0.mp4.json
130,NaN,NaN,NaN,ss01964,NaN,NaN,<NA>,day,NaN,NaN,NaN,NaN,57,VM_2026-08-12_VRDN-screen-week7_batch1_f64,NaN,15-10-2026,SS01964_31-07_day_L0.mp4.json

Load pupae batch

In [14]:
#I do not want to have to do this again, just automate it
pupae_batch_folder = "VM_2026-08-13_VRDN-screen-week7_batch2_f30"

pupae_batch_csv = read_pupae_counts(pupae_batch_folder).copy() #this will only work if you've "connected" to the windingm folder by opening it in your laptop

pupae_batch_csv["pupae_source_row"] = pupae_batch_csv.index + 1
for d in [pupae_batch_csv]:
    d["pupae_batch_folder"] = pupae_batch_folder

pupae_batch_csv["dataset"] = pupae_batch_csv["dataset"].astype(str).str.strip() #making sure it's clean strings
pupae_batch_csv["dataset"] = pupae_batch_csv["dataset"].str.split("predictions/", n=1).str[-1]
pupae_batch_csv["dataset"] = pupae_batch_csv["dataset"].str.replace(
    r'(\d{1,2})([-_])(\d{1,2})([-_])(day|night)\b',
    r'\1-\2_\4',
    regex=True
)
pattern = r'(?i)(?P<experiment>.+?)[_-](?P<date>\d{1,2}-\d{2})[_-](?P<time>day|night)\_'
pupae_batch_csv[["condition", "date", "time"]] = pupae_batch_csv["dataset"].str.extract(pattern, expand=True)

#extract date of experiment
date_extracted = pupae_batch_csv["date"].str.extract(r'(\d{1,2}[-_]\d{1,2})', expand=False)
date_norm = date_extracted.str.replace("_", "-", regex=False)
#pupae_batch_csv["staging_date_clean_dt"] = pd.to_datetime(date_norm + f"-{year}", format="%d-%m-%Y", errors="coerce")

#calculate Pupae total
pupae_batch_csv["L_value"] = pupae_batch_csv["dataset"].str.extract(r'(?i)_L(\d+)', expand=False).astype("Int64")
pupae_batch_csv["Pupae"] = pupae_batch_csv["pupae_count"] + pupae_batch_csv["L_value"] #for clarity, the new original sheets should have a column called pupae_final rather than Pupae"

for col in match_cols:
    if col in pupae_batch_csv.columns:
        pupae_batch_csv[col] = (
            pupae_batch_csv[col]
            .astype("string")
            .str.replace("\u00a0", " ", regex=False)
            .str.strip()
            .str.lower()
        )

today = pd.Timestamp.today().strftime("%d-%m-%Y")
pupae_batch_csv["last_edit"] = today

print(
    pupae_batch_csv[
        [
            "pupae_source_row",
            "dataset",
            "condition",
            "date",
            "time",
            "Pupae",
            "pupae_count",
            "pupae_batch_folder",
        ]
    ].to_string(index=False)
)

 pupae_source_row                         dataset condition  date  time  Pupae  pupae_count                         pupae_batch_folder
                1      B6_27-07_night_L0.mp4.json        b6 27-07 night    120          120 VM_2026-08-13_VRDN-screen-week7_batch2_f30
                2     A21_29-07_NIGHT_L0.mp4.json       a21 29-07 night     76           76 VM_2026-08-13_VRDN-screen-week7_batch2_f30
                3     B11_29-07_night_L0.mp4.json       b11 29-07 night     76           76 VM_2026-08-13_VRDN-screen-week7_batch2_f30
                4     B10_29-07_night_L0.mp4.json       b10 29-07 night    244          244 VM_2026-08-13_VRDN-screen-week7_batch2_f30
                5      B9_29-07_night_L0.mp4.json        b9 29-07 night    144          144 VM_2026-08-13_VRDN-screen-week7_batch2_f30
                6     b20_29-07_NIGHT_L0.mp4.json       b20 29-07 night    129          129 VM_2026-08-13_VRDN-screen-week7_batch2_f30
                7     A13_29-07_night_L0.mp4.json       a13 29-07 night     19           19 VM_2026-08-13_VRDN-screen-week7_batch2_f30
                8  SS4410_29-07_night_L0.mp4.json    ss4410 29-07 night    110          110 VM_2026-08-13_VRDN-screen-week7_batch2_f30
                9      B8_29-07_night_L0.mp4.json        b8 29-07 night    175          175 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               10     A16_29-07_night_L0.mp4.json       a16 29-07 night    130          130 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               11      A7_29-07_night_L0.mp4.json        a7 29-07 night    138          138 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               12 ss55093_29-07_NIGHT_L0.mp4.json   ss55093 29-07 night    111          111 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               13      B4_29-07_night_L0.mp4.json        b4 29-07 night    180          180 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               14      A8_29-07_night_L0.mp4.json        a8 29-07 night    199          199 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               15     A12_29-07_night_L0.mp4.json       a12 29-07 night     30           30 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               16     A15_29-07_night_L0.mp4.json       a15 29-07 night     96           96 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               17      A5_29-07_night_L0.mp4.json        a5 29-07 night    224          224 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               18      A9_29-07_night_L0.mp4.json        a9 29-07 night     56           56 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               19   ss59598_31-07_day_L0.mp4.json   ss59598 31-07   day    167          167 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               20     B18_29-07_night_L0.mp4.json       b18 29-07 night    159          159 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               21     B14_29-07_night_L0.mp4.json       b14 29-07 night     86           86 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               22      B5_29-07_night_L0.mp4.json        b5 29-07 night    108          108 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               23     A19_29-07_night_L0.mp4.json       a19 29-07 night    114          114 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               24     a22_29-07_NIGHT_L0.mp4.json       a22 29-07 night    113          113 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               25      b6_30-07_NIGHT_L0.mp4.json        b6 30-07 night    131          131 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               26      A6_29-07_night_L0.mp4.json        a6 29-07 night     89           89 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               27     a23_29-07_NIGHT_L0.mp4.json       a23 29-07 night    116          116 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               28     A11_29-07_night_L0.mp4.json       a11 29-07 night     76           76 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               29 ss01624_29-07_night_L0.mp4.json   ss01624 29-07 night     31           31 VM_2026-08-13_VRDN-screen-week7_batch2_f30
               30     A19_30-07_NIGHT_L0.mp4.json       a19 30-07 night     76           76 VM_2026-08-13_VRDN-screen-week7_batch2_f30

In [15]:
#Add safety information to the sheet - default do not merge automatically 

#are there any condition duplicates? do not merge automatically
raw_counts = (
    sheet_df.groupby(match_cols, dropna=False)
    .size()
    .rename("raw_sheet_matches")
    .reset_index()
)

sheet_df_wcounts = sheet_df.merge(
    raw_counts,
    on=match_cols,
    how="left"
)

#Leave the Pupae alone if the cell is not empty
pupae_s = sheet_df_wcounts["Pupae"].astype("string").str.strip()
pupae_empty = (
    sheet_df_wcounts["Pupae"].isna()
    | pupae_s.eq("")
    | pupae_s.str.lower().isin(["nan", "<na>", "none"])
)

#pupae_empty = (
    #sheet_df_wcounts["Pupae"].isna()
#)

sheet_df_wcounts["safe_for_pupae_merge"] = (
    sheet_df_wcounts["raw_sheet_matches"].eq(1)
    & pupae_empty
)
sheet_df_wcounts["pupae_merge_safety_reason"] = np.select(
    [
        sheet_df_wcounts["raw_sheet_matches"].gt(1),
        ~pupae_empty,
        sheet_df_wcounts["safe_for_pupae_merge"],
    ],
    [
        "duplicate condition/date/time in Google Sheet",
        "existing Pupae already present",
        "safe to merge",
    ],
    default="not safe to merge"
)

sheet_df_wcounts["safe_for_pupae_merge"] = (
    sheet_df_wcounts["safe_for_pupae_merge"]
    .fillna(False)
)
sheet_df_wcounts["pupae_merge_safety_reason"] = (
    sheet_df_wcounts["pupae_merge_safety_reason"]
    .fillna("not safe to merge")
)


sheet_df_wcounts = standardise_missing_values(sheet_df_wcounts)

sheet_df_wcounts_clean = sheet_df_wcounts[["condition", "date", "time", "raw_sheet_matches", "safe_for_pupae_merge", "pupae_merge_safety_reason"]].copy() #avoid column duplicates
sheet_df_wcounts_clean["pupae_merge_safety_reason"].value_counts()

sheet_df_wcounts["pupae_merge_safety_reason"].value_counts()

sheet_safety_lookup = (
    sheet_df_wcounts_clean
    .groupby(match_cols, dropna=False)
    .agg(
        raw_sheet_matches=("raw_sheet_matches", "max"),
        safe_for_pupae_merge=("safe_for_pupae_merge", "any"),
        pupae_merge_safety_reason=(
            "pupae_merge_safety_reason",
            lambda x: "; ".join(sorted(set(x.dropna().astype(str))))
        ),
    )
    .reset_index()
)
# rows are dropped because the duplicate conditions become one - they're still void anyway
#sheet_safety_lookup["safe_for_pupae_merge"].value_counts()

In [16]:
#this is the helpful information for pupae_batch_csv ... 
pupae_diag = pupae_batch_csv.merge(
    sheet_safety_lookup, 
    on=match_cols, 
    how="left", 
    validate="m:1"
)
pupae_diag["raw_sheet_matches"] = (
    pupae_diag["raw_sheet_matches"]
    .fillna(0)
    .astype(int)
)

pupae_diag["safe_for_pupae_merge"] = (
    pupae_diag["safe_for_pupae_merge"]
    .fillna(False)
)

pupae_diag["pupae_merge_safety_reason"] = (
    pupae_diag["pupae_merge_safety_reason"]
    .fillna("condition/date/time not found in Google Sheet")
)

pupae_for_merge = pupae_diag.loc[
    pupae_diag["safe_for_pupae_merge"]
].copy()

n_pupae = len(pupae_batch_csv)
n_pupae_safe_match = len(pupae_for_merge)
print(f"Pupae rows with safe sheet match: {n_pupae_safe_match}/{n_pupae}")

if n_pupae_safe_match == n_pupae:
    print("All pupae counts matched successfully.")
else:
    print(f"{n_pupae - n_pupae_safe_match} pupae rows did not match automatically.")

merged = sheet_df_wcounts.merge(
    pupae_for_merge,
    on=match_cols,
    how="left",
    suffixes=("", "_from_pupae"),
    indicator="merge_status",
)

matched_pupae_row = merged["merge_status"].eq("both") 

merged.loc[matched_pupae_row, "Pupae"] = merged.loc[
    matched_pupae_row,
    "Pupae_from_pupae"
]
merged.loc[matched_pupae_row, "pupae_batch_folder"] = merged.loc[
    matched_pupae_row,
    "pupae_batch_folder_from_pupae"
]

#creating the columns first to then populate them. 
if "last_edit_from_pupae" in merged.columns:
    merged.loc[matched_pupae_row, "last_edit"] = merged.loc[
        matched_pupae_row,
        "last_edit_from_pupae"
    ]

merged[["condition", "date", "time", "Pupae", "Pupae_from_pupae", "dataset", "last_edit", "pupae_batch_folder"]].head(30)

Pupae rows with safe sheet match: 3/30
27 pupae rows did not match automatically.

,condition,date,time,Pupae,Pupae_from_pupae,dataset,last_edit,pupae_batch_folder
0,ss02758,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
1,ss55093,29-07,night,111,111,NaN,15-10-2026,VM_2026-08-13_VRDN-screen-week7_batch2_f30
2,ss01624,29-07,night,31,31,NaN,15-10-2026,VM_2026-08-13_VRDN-screen-week7_batch2_f30
3,ss54410,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
4,ss01267,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
5,ss37748,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
6,ss04267,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
7,ss37748,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
8,ss37746,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
9,ss53586,29-07,night,8,<NA>,NaN,<NA>,manual
10,ss01712,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
11,ss01782,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
12,ss37768,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
13,split-2,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
14,mb214b,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
15,ss54035,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
16,ss01744,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
17,ss02128,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
18,ss38056,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
19,ss04610,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
20,ss04169,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
21,ss553306,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
22,ss01688,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
23,ss553086,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
24,ss53561,29-07,night,57,<NA>,NaN,<NA>,VM_2026-08-12_VRDN-screen-week7_batch1_f64
25,ss55972,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
26,ss22943,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
27,ss04631,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
28,ss04241,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>
29,ss536219,29-07,night,<NA>,<NA>,NaN,<NA>,<NA>

In [ ]:
# Append counts requiring manual review below the existing sheet rows.
pupae_unmatched = pupae_diag.loc[
    ~pupae_diag["safe_for_pupae_merge"]
].copy()

# Keep the reason alongside the filename for review in the uploaded sheet.
pupae_unmatched["manual_inspection_reason"] = pupae_unmatched["pupae_merge_safety_reason"]

final_df = pd.concat(
    [merged, pupae_unmatched], 
    ignore_index=True
)

In [ ]:
drop_cols = [
    "merge_status",
    "raw_sheet_matches", 
    "safe_for_pupae_merge",
    "pupae_merge_safety_reason", 
    "_merge", 
    "L_value", 
    "raw_sheet_matches", 
    "Pupae_batch_folder_from_pupae", 
    "pupae_count",
    "pupae_source_row",
    "Pupae_from_pupae",
    "pupae_batch_folder_from_pupae", 
    "raw_sheet_matches_from_pupae",
    "last_edit_from_pupae", 
    "safe_for_pupae_merge_from_pupae", 
    "pupae_merge_safety_reason_from_pupae"
]

suffix_drop_cols = [
    col for col in final_df.columns
    if col.endswith("_from_pupae")
]

cols_to_drop = drop_cols + suffix_drop_cols

if pupae_unmatched.empty:
    drop_cols += [
        "pupae_count",
        "Pupae_from_pupae",
        "dataset",
        "manual_inspection_reason",
        "pupae_source_row"
    ]

final_df = final_df.drop(
    columns=drop_cols + suffix_drop_cols,
    errors="ignore"
)

final_df["pupae_batch_folder"].value_counts()

In [ ]:
# Void experiments with fewer than 100 or more than 250 pupae.
# Apply after appending manual-review rows so those counts are checked too.
import sys

repo_root = Path.cwd()
if not (repo_root / "scripts" / "pupae_counting.py").exists():
    repo_root = repo_root.parent
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

from scripts.pupae_counting import flag_void_pupae_counts

final_df = flag_void_pupae_counts(final_df)
final_df[["Pupae", "amendments", "comments"]]

In [19]:
upload_df = final_df.copy()

#upload_df = upload_df.fillna("")
upload_df = upload_df.astype(str)

worksheet.clear()

worksheet.update(
    [upload_df.columns.tolist()] + upload_df.values.tolist()
)

{'spreadsheetId': '1g8utRFF02OVMsuhlnVtWP37OPk-AR87k7LYKUXkWiY0',
 'updatedRange': 'Sheet1!A1:R159',
 'updatedRows': 159,
 'updatedColumns': 18,
 'updatedCells': 2862}